GET http://localhost:3005/api/v1/xin-nghi/danh-sach-full

###
GET http://localhost:3005/api/v1/nhan-vien/danh-sach-nhan-vien-theo-acc/votienthanh
###

GET  http://localhost:3005/api/v1/xin-nghi/curent